name: Dockerize backend

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the source
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action
        width:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/villakostnader-backend

      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/villakostnader-backend
